import { StyleSheet } from 'react-native';
import { scale } from '../constants';

export const homeStyles = StyleSheet.create({
  home: {
    flex: 1,
    padding: scale(24),
    paddingTop: scale(10),
    alignItems: 'center',
  },
  subtitle1: {
    fontSize: scale(70),
    color: '#1B5E20',
    marginBottom: scale(1),
  },
  subtitle2: {
    fontSize: scale(30),
    color: '#1B5E20',
    marginBottom: scale(20),
    fontWeight: '700',
    letterSpacing: 0.7,
  },
  subtitle: {
    fontSize: scale(17),
    color: '#546E7A',
    marginBottom: scale(16),
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: scale(20),
    padding: scale(24),
    width: '100%',
    marginBottom: scale(20),
    shadowColor: '#1B5E20',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  infoTitle: {
    fontSize: scale(18),
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: scale(18),
    color: '#1B5E20',
  },
  classGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  classItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F9F7',
    padding: scale(12),
    borderRadius: scale(24),
    margin: scale(5),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  classEmoji: {
    fontSize: scale(22),
    marginRight: scale(8),
  },
  classText: {
    fontSize: scale(14),
    color: '#37474F',
    fontWeight: '600',
  },
  primaryBtn: {
    backgroundColor: '#1B5E20',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(18),
    paddingHorizontal: scale(24),
    borderRadius: scale(16),
    width: '100%',
    marginBottom: scale(12),
    shadowColor: '#1B5E20',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryBtnText: {
    color: '#fff',
    fontSize: scale(18),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  secondaryBtn: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(18),
    paddingHorizontal: scale(24),
    borderRadius: scale(16),
    width: '100%',
    borderWidth: 2,
    borderColor: '#1B5E20',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  secondaryBtnText: {
    color: '#1B5E20',
    fontSize: scale(18),
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  permText: {
    fontSize: scale(17),
    color: '#546E7A',
    marginBottom: scale(12),
    fontWeight: '500',
  },
  btn: {
    backgroundColor: '#1B5E20',
    paddingVertical: scale(16),
    paddingHorizontal: scale(32),
    borderRadius: scale(12),
    marginTop: scale(20),
    shadowColor: '#1B5E20',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  btnText: {
    color: '#fff',
    fontSize: scale(16),
    fontWeight: '700',
  },
});
